name: Ilia Luchnikov
description: Here I host my blogposts and some information about my projects

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /about
domain_name: "http://LuchnikovI.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "LuchnikovI.github.io"
author: "Ilia Luchnikov"

# Disqus config
disqus-shortname: ""
